plugins:
  single_login_shared_enabled:
    default: true
    client: false

  single_login_shared_username:
    default: "shared_account"
    client: false

  single_login_shared_timeout_minutes:
    default: 5
    min: 1
    max: 1440
