plugins:
  single_login_shared_enabled:
    default: true
    client: true  # for testingreasons

  # kommasepariert: Antoinette,Louis
  single_login_shared_usernames:
    default: "Antoinette,Louis"
    client: true  # for testingreasons

  # nur noch statischer Timeout (in Minuten)
  single_login_shared_max_session_minutes:
    default: 2
    min: 1
    max: 1440
    client: true  # for testingreasons
